- name: Install nginx required  and helper packages
  package: name={{ item }} state=present
  with_items:
    - nginx-extras
    - uwsgi
    - uwsgi-plugin-python3
    - php-fpm
    - libnginx-mod-http-subs-filter

- name: Add http server  user to shadow group, so it can authenticate Admin Console
  user:
    name: "{{ apache_user }}"
    groups: shadow

- name: Remove the nginx default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
