- name: Get the tools to use the Pico board
  package: 
    name:
      - minicom
    state: present

- name: Get the Pico firmware
  get_url:
    url: "{{ iiab_download_url }}/pico_micropython_20210121.uf2"
    dest: "{{ downloads_dir }}"

# RECORD PICO AS INSTALLED

- name: Set pico_installed to True
  set_fact:
    pico_installed: True

- name: Add pico_installed to True in {{ iiab_state_file }}
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^pico_installed'
    line: 'pico_installed: True'

