- name: Get the tools to use the Pico board
  package:
    - minicom
  state: present
  when: not rpi_model == None and pico_install == True

- name: Get the Pico firmware
  get_url:
    url: "{{ iiab_download_url }}/"pico_micropython_20210121.uf2"
    dest: "{{ downloads_dir }}"

# RECORD PICO AS INSTALLED

- name: "Set 'pico_installed: True'"
  set_fact:
    pico_installed: True

- name: "Add 'pico_installed: True' to {{ iiab_state_file }}"
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^pico_installed'
    line: 'pico_installed: True'
