- name: Create user jupyter
  user:
    name: jupyter

- name: Make the directories to hold jupyter config
  file:
    state: directory
    path: '{{ item }}'
    owner: jupyter
  with_items:
     - '{{ jupyterhub_venv }}'
     - '{{ jupyterhub_venv }}/etc/jupyter'
     - '{{ jupyterhub_venv }}/etc/jupyterhub'
     - '{{ jupyterhub_venv }}/etc/systemd'
     - /library/jupyterhub

- name: "Set 'nodejs_install: True' and 'nodejs_enabled: True'"
  set_fact:
    nodejs_install: True
    nodejs_enabled: True

- name: NODEJS - run 'nodejs' role (attempt to install & enable Node.js)
  include_role:
    name: nodejs

- name: FAIL (STOP THE INSTALL) IF 'nodejs_installed is undefined'
  fail:
    msg: "Jupyter install cannot proceed, as Node.js is not installed."
  when: nodejs_installed is undefined

- name: use npm to install configurable http proxy
  npm:
      name: configurable-http-proxy
      global: yes
      state: latest

- name: Use pip to install into a virtual environment
  pip:
    name:
       - pip
       - wheel
       - ipywidgets
       - jupyterhub
       - jupyterlab
       - jupyterhub_firstuseauthenticator
       - jupyterhub-systemdspawner
    virtualenv: "{{ jupyterhub_venv }}"    # /opt/iiab/jupyter
    virtualenv_site_packages: no
    virtualenv_command: /usr/bin/virtualenv
    virtualenv_python: python3
    extra_args: "--no-cache-dir"
  become: True
  become_user: jupyter
  when: internet_available
    
- name: Put a sudoer file to permit systemdspawner to  startup as user:jupyter
  template:
     src: 015_jupyterhub.sudoers.d
     dest: /etc/sudoers.d/015_jupyterhub
     mode: 0440

- name: Patch the systemdspawner to use {{ jupyterhub_venv }} for it's "/run" directory
  shell: sed -i -e's|^RUN_ROOT.*|RUN_ROOT = {{ jupyterhub_venv }}|' {{ jupyterhub_venv }}/lib/*/site-packages/systemdspawner/systemdspawner.py

- name: Install the config file for jupyterhub
  template:
      src: jupyterhub_config.py
      dest: '{{ jupyterhub_venv }}/etc/jupyterhub/'

- name: Use systemd to start jupyterhub
  become: True
  template:
      src: jupyterhub.service
      dest: /etc/systemd/system/

- name: A script to start jupyterhub without systemd for debug
  template:
      dest: '{{ jupyterhub_venv }}'
      src: start-debug
      mode: 0755
