- name: Get the linux packages that run on IIAB for local mail service
  package:
    name:
      - dovecot-imapd
      - logwatch
      - roundcube
      - roundcube-core
      - roundcube-plugins-extra
      - roundcube-plugins
      - roundcube-mysql
    state: present

- name: Create a directory for mail
  file:
      state: directory
      path: '{{ content_base }}/mail'
      owner: dovecot
      group: dovecot
       
- name: Create a directory for exim4 data
  file:
      state: directory
      path: '{{ content_base }}/exim4/bsmtp'
      owner: Debian-exim
      group: Debian-exim
       
- name: Copy dovecot config files where they belong
  copy:
    src: "{{ item }}"
    dest: /etc/dovecot/
  with_fileglob:
    - dovecot/*

- name: Copy exim config files where they belong
  copy:
    src: "{{ item }}"
    dest: /etc/exim4/
  with_fileglob:
    - exim4-conf/*

- name: Copy roundcube config files where they belong
  copy:
    src: "{{ item }}"
    dest: /etc/roundcube/
  with_fileglob:
    - roundcube/*

- name: "Set 'mongodb_install: True'"
  set_fact:
    mongodb_install: True

- name: MONGODB - run 'mongodb' role (attempt to install MongoDB)
  include_role:
    name: mongodb


- name: "Set 'nodejs_install: True' and 'nodejs_enabled: True'"
  set_fact:
    nodejs_install: True
    nodejs_enabled: True

- name: NODEJS - run 'nodejs' role (attempt to install & enable Node.js)
  include_role:
    name: nodejs

- name: FAIL (STOP THE INSTALL) IF 'nodejs_installed is undefined'
  fail:
    msg: "eMule install cannot proceed, as Node.js is not installed."
  when: nodejs_installed is undefined

- name: Install nginx config file for Roundcube
  template:
      src: emule.conf.j2
      dest: '{{ nginx_conf_dir }}/emule.conf'

- name: Tell roundcube where to find the sqlite database
  template:
      src: roundcube.conf
      dest: /etc/dbconfig-common/roundcube.conf

- name: Check of pear module is installed (fails if it does)
  stat:
      path: /usr/share/php/Net/IDNA2.php
  register: idna2

- name: Install a pear module required by roundcube
  shell: pear install channel://pear.php.net/net_idna2-0.2.0
  when: not idna2.stat.exists

- name: Execute the shell script which initializes MySQL for dovecot
  shell:
     cmd: ./setup_dovecot.sh
     chdir: '{{ iiab_dir }}/roles/emule/files/dovecot/'
