# kolibri_install: False
# kolibri_enabled: False

# kolibri_language: en    # ar,bn-bd,en,es-es,fa,fr-fr,hi-in,mr,nyn,pt-br,sw-tz,ta,te,ur-pk,yo,zu

# kolibri_http_port: 8009

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

# 2019-09-27: Pinning to a particular version is unfortunately NOT supported
# with our new apt approach (.deb installer) at this time.
# 2019-06-21: Uncomment this pinning line if you want a particular version of
# Kolibri rather than the "latest", e.g. to work around after 0.12.4's bug:
# kolibri_version: 0.12.3
# https://github.com/iiab/iiab/issues/1675
# https://github.com/learningequality/kolibri/issues/5664

kolibri_deb_url: http://ppa.launchpad.net/learningequality/kolibri/ubuntu/pool/main/k/kolibri-source/kolibri_0.12.9-0ubuntu2_all.deb

# Kolibri folder to store its data and configuration files.
kolibri_home: "{{ content_base }}/kolibri"    # /library/kolibri

kolibri_url_without_slash: /kolibri
kolibri_url: "{{ kolibri_url_without_slash }}/"    # /kolibri/

kolibri_exec_path: /usr/bin/kolibri

kolibri_user: kolibri    # Whereas a vanilla install of Kolibri auto-identifies
# and saves a 'desktop' user like {iiab-admin, pi} to /etc/kolibri/username,
# towards guaranteeing access to USB devices, per:
# https://kolibri.readthedocs.io/en/latest/install.html#changing-the-owner-of-kolibri-system-service

# To populate /library/kolibri with essential/minimum files and dirs.  This
# provisions Kolibri with facility name, admin acnt / password, preset type,
# and language.  You can set this to 'False' when reinstalling Kolibri:
kolibri_provision: True

kolibri_facility: Kolibri-in-a-Box

kolibri_admin_user: Admin
kolibri_admin_password: changeme

# Kolibri Preset type: formal, nonformal, informal
kolibri_preset: formal
