- name: Install nginx config for nternetarchive for short URL http://box/archive (if debuntu and internetarchive_enabled)
  template:
    src: internetarchive.nginx.conf
    path: /etc/nginx/conf.d
  when: is_debuntu and internetarchive_enabled

- name: Remove config /etc/nginx/conf.d/internetarchive.conf (if debuntu and not internetarchive_enabled)
  file:
    path: /etc/nginx/conf.d/internetarchive.conf
    state: absent
  when: is_debuntu and not internetarchive_enabled

 # RESTART/ENABLE SYSTEMD SERVICE
- name: Disable 'internetarchive' systemd service (if not internetarchive_enabled)
  systemd:
    name: internetarchive
    enabled: no
  when: not internetarchive_enabled

- name: Enable & Restart 'internetarchive' systemd service (if internetarchive_enabled)
  systemd:
    name: internetarchive
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: internetarchive_enabled | bool

- name: Restart to enable/disable http://box/archive (not just http://box:{{ internetarchive_port }})
  systemd:
    name: nginx    # httpd or apache2
    state: restarted
  when: internetarchive_enabled | bool

- name: Add 'internetarchive' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"
    section: internetarchive
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: name
      value: Internet Archive Offline
    - option: description
      value: '"Dweb-mirror is intended to make the Internet Archive experience and UI available offline."'
    - option: internetarchive_enabled
      value: "{{ internetarchive_enabled }}"
