#!/bin/bash
systemctl disable hostapd
systemctl disable dhcpd
systemctl enable wpa_supplicant
systemctl daemon-reload

# let the networking.service bring up the wifi via wpa_supplicant
cat << EOF > /etc/network/interfaces.d/wan
auto wlan0
iface wlan0 inet dhcp
EOF


# Temporary promiscuous-mode workaround for RPi's WiFi "10SEC disease"
# Set wlan0 to promiscuous when AP's OFF (for possible WiFi gateway)
# SEE ALSO iiab-hotspot-on + /usr/libexec/iiab-startup.sh
# https://github.com/iiab/iiab/issues/638#issuecomment-355455454
if grep -qi raspbian /etc/*release; then
    ip link set dev wlan0 promisc on
fi

sed -i -e "s/^hostapd_enabled.*/hostapd_enabled = False/" /etc/iiab/iiab.ini
echo
echo rebooting in 5 seconds
echo
sleep 5
reboot
