#!/bin/bash
# enable the upstream wlan0 for rpi3 and rpi-w

# will fail if supplicant is already running
/usr/bin/killall wpa_supplicant
/sbin/wpa_supplicant -iwlan0 -c/etc/wpa_supplicant/wpa_supplicant.conf &
sleep 1
dhclient wlan0

# may need to change the iptables
GATEWAY=`route -n | awk '/UG/ { print $8 }'
# Set the way device -- defaults to wlan0_ap
if [ "$GATEWAY" == "wlan0" ]; then
   sed -i -e 's/^IIAB_WAN_DEVICE.*/IIAB_WAN_DEVICE=wlan0/' /etc/iiab/iiab.env
else
   sed -i -e 's/^IIAB_WAN_DEVICE.*/IIAB_WAN_DEVICE=wlan0_ap/' /etc/iiab/iiab.env
fi
sed -i -e 's/.*iiab_network_mode_applied.*/iiab_network_mode_applied: Gateway/ /etc/iiab/iiab.ini

# execute script that generates and saves iptables, after changes to iiab.env
/usr/bin/iiab-gen-iptables
