#!/bin/bash

systemctl enable iiab-startup.service

# following used in iiab-startup.sh to set/clear promiscuous mode in wifi driver
sed -i -e "s/^hostapd_enabled.*/hostapd_enabled = True/" /etc/iiab/iiab.ini

echo
echo rebooting in 5 seconds
echo
sleep 5
reboot
