# "How do i fail a task in Ansible if the variable contains a boolean value?
# I want to perform input validation for Ansible playbooks"
# https://stackoverflow.com/questions/46664127/how-do-i-fail-a-task-in-ansible-if-the-variable-contains-a-boolean-value-i-want/46667499#46667499

# We assume 0-init/tasks/validate_vars.yml has DEFINITELY been run, so no need
# to re-check whether vars are defined here.  As Ansible vars cannot be unset:
# https://serverfault.com/questions/856729/how-to-destroy-delete-unset-a-variable-value-in-ansible

- name: Assert that "moodle_install is sameas true" (boolean not string etc)
  assert:
    that: moodle_install is sameas true
    fail_msg: "PLEASE SET 'moodle_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "moodle_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: moodle_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'moodle_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- name: Install Moodle if 'moodle_installed' not defined, e.g. in {{ iiab_state_file }}    # /etc/iiab/iiab_state.yml
  include_tasks: install.yml
  when: moodle_installed is undefined


# - name: Enable 'postgresql-iiab' systemd service, if moodle_enabled
#   systemd:
#     name: postgresql-iiab
#     deamon_reload: yes
#     state: started
#     enabled: yes
#   when: moodle_enabled | bool
#
# # if the only service using the backend db disable if not running
# - name: Disable 'postgresql-iiab' systemd service, if 'not moodle_enabled and not (pathagar_enabled is defined and pathagar_enabled)'
#   systemd:
#     name: postgresql-iiab
#     state: stopped
#     enabled: no
#   when: not moodle_enabled and not (pathagar_enabled is defined and pathagar_enabled)

- name: "Set 'postgresql_enabled: True' if moodle_enabled"
  set_fact:
    postgresql_enabled: True
  when: moodle_enabled | bool

- name: "Set 'postgresql_enabled: False' if 'not moodle_enabled and not (pathagar_enabled is defined and pathagar_enabled)'"
  set_fact:
    postgresql_enabled: False
  when: not moodle_enabled and not (pathagar_enabled is defined and pathagar_enabled)

- name: POSTGRESQL - run 'postgresql' role (Enable&Start or Disable&Stop PostgreSQL)
  include_role:
    name: postgresql


#- name: Enable/Disable/Restart Apache if primary
- name: SHIM FOR NOW SO ALWAYS DO THE...Enable/Disable/Restart Apache
  include_tasks: apache.yml
  #when: not nginx_enabled

- name: Enable/Disable/Restart NGINX if primary
  include_tasks: nginx.yml
  when: nginx_enabled | bool


- name: Add 'moodle' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
    section: moodle
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
  with_items:
    - option: name
      value: Moodle
    - option: description
      value: '"Access the Moodle learning management system."'
    - option: "moodle_base"
      value: "{{ moodle_base }}"
    - option: moodle_enabled
      value: "{{ moodle_enabled }}"
