- name: "Yarn | GPG"
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: "Yarn | Ensure Debian sources list file exists"
  file:
    path: /etc/apt/sources.list.d/yarn.list
    owner: root
    mode: '0644'
    state: touch

- name: "Yarn | Ensure Debian package is in sources list"
  lineinfile:
    dest: /etc/apt/sources.list.d/yarn.list
    regexp: 'deb https://dl.yarnpkg.com/debian/ stable main'
    line: 'deb https://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: "Yarn | Update APT cache"
  apt:
    update_cache: yes

- name: "Yarn | Install"
  package:
    name: yarn
    state: latest
  when: internet_available and is_debuntu


# RECORD Yarn AS INSTALLED

- name: "Set 'yarn_installed: True'"
  set_fact:
    yarn_installed: True

- name: "Add 'yarn_installed: True' to {{ iiab_state_file }}"
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^yarn_installed'
    line: 'yarn_installed: True'
