# osm_vector_maps_install: True
# osm_vector_maps_enabled: True

# iiab_map_url : http://download.iiab.io/content/OSM/vector-tiles/maplist/hidden
# vector_map_path: "{{ content_base }}/www/osm-vector-maps"

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!
#osm_map_url: https://github.com/iiab/maps/raw/master
# for testing, use the new unpublished version of regions.json
osm_repo_url: https://raw.githubusercontent.com/georgejhunt/maps/stage1
archive_org_url: https://archive.org/download
satellite_version: satellite_z0-z9_v3.mbtiles
maps_branch: test
