- name: Download & install python-dateutil, sqlite3
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-dateutil

- name: Create directory /opt/iiab/captive-portal for scripts & templates
  file:
    path: /opt/iiab/captive-portal
    state: directory
    owner: "{{ apache_user }}"

- name: 'Copy scripts: checkurls, capture-wsgi.py'
  template:
    src: "{{ item.src }}"
    dest: /opt/iiab/captive-portal/
    mode: "{{ item.mode }}"
  with_items:
    - { src: roles/captive-portal/templates/checkurls, mode: '0644' }
    - { src: roles/captive-portal/templates/capture-wsgi.py, mode: '0755' }

- name: 'Copy templates: simple.template, mac.template'
  copy:
    src: "{{ item }}"
    dest: /opt/iiab/captive-portal/
  with_items:
    - roles/captive-portal/files/simple.template
    - roles/captive-portal/files/mac.template

- name: Copy unit file for uWSGI service
  template:
    src: uwsgi-captive-portal.service
    dest: /etc/systemd/system/

- name: Start or restart server which responds to browsers trying to detect a captive portal
  systemd: 
    name: uwsgi-captive-portal.service
    state: restarted
  when: captive_portal_enabled | bool

- name: Stop uWSGI server if captive portal has been disabled
  systemd: 
    name: uwsgi-captive-portal.service
    state: stopped
  when: not captive_portal_enabled | bool

- name: Run iiab-uncatch to generate diversion lists for dnsmasq and apache2
  shell: /usr/bin/iiab-uncatch
     
- name: Install nginx's captive-portal.conf from template if captive_portal_enabled
  template:
    src: roles/captive-portal/templates/captive-portal-nginx.conf
    dest: /etc/nginx/sites-available
    owner: root
    group: root
    mode: 0644
  when: captive_portal_enabled | bool

- name: Enable Apache's captive-portal.conf if captive_portal_enabled (debuntu)
  file:
    src: /etc/nginx/sites-available/captive-portal-nginx.conf
    path: /etc/nginx/sites-enabled/captive-portal-nginx.conf
    state: link
  when: captive_portal_enabled and is_debuntu


- name: Disable nginx's captive-portal.conf if not captive_portal_enabled (debuntu)
  file:
    path: /etc/nginx/sites-enabled/001-captive-portal.conf
    state: absent
  when: not captive_portal_enabled and is_debuntu

- name: Make sure dnsmasq is not diverting if not captive_portal_enabled
  file:
    path: /etc/dnsmasq.d/capture
    state: absent
  when: not captive_portal_enabled

- name: Add 'captive_portal_installed' variable values to {{ iiab_state_file }}
  lineinfile:
    dest: "{{ iiab_state_file }}"
    regexp: '^captive_portal_installed'
    line: 'captive_portal_installed: True'
    state: present

#- name: Restart dnsmasq
#  systemd:
#    name: dnsmasq
#    state: restarted
#  when: dnsmasq_enabled | bool

# ABOVE DOES NOT WORK ON UBUNTU 16.04 -- what follows is a crude hack (seems to work!)

- name: Stop dnsmasq
  systemd:
    name: dnsmasq
    state: stopped
  when: dnsmasq_enabled | bool

- name: Start dnsmasq
  systemd:
    name: dnsmasq
    state: started
  when: dnsmasq_enabled | bool
  
