- name: Make sure the Map Test Page directory exists
  file:
    path: '{{ vector_map_path }}/maplist/assets'
    state: directory
    mode: '0755'

- name: Make space for the viewer assets
  file:
    path: '{{ vector_map_path }}/viewer/assets'
    state: directory
    mode: '0755'

- name: Make space for the viewer tiles
  file:
    path: '{{ vector_map_path }}/viewer/tiles'
    state: directory
    mode: '0755'

- name: Make space for the installer tiles
  file:
    path: '{{ vector_map_path }}/installer'
    state: directory
    mode: '0755'

- name: Copy the map catalog to /etc/iiab/map-catalog.json
  get_url:
    url: "{{ map_catalog_url }}/map-catalog.json"
    dest: /etc/iiab/

- name: Check for existence of cities database
  stat:
    path: "{{ vector_map_path }}/cities1000.sqlite"
  register: cities_installed

- name: Fetch the city database
  get_url:
    url: "{{ iiab_map_url }}/regional-resources/cities1000.sqlite"
    dest: '{{ vector_map_path }}/viewer/cities1000.sqlite'
  when: not cities_installed.stat.exists

- name: Create a link to osm catalog in /common/assets
  file:
    src: "/etc/iiab/map-catalog.json"
    dest: "{{ doc_root }}/common/assets/map-catalog.json"
    state: link

- name: Create a link to osm catalog in {{ vector_map_path }}/maplist/assets
  file:
    src: "/etc/iiab/map-catalog.json"
    dest: "{{ vector_map_path }}/maplist/assets/map-catalog.json"
    state: link

- name: Download the JavaScript bundle with OpenLayers (main.js) for test page http://box/maps/maplist
# At this point, fetches from github.com/georgejhunt/maps from test branch
  get_url:
    url: '{{ item }}' 
    dest: '{{ vector_map_path }}/maplist/'
  with_items:
    - "{{ osm_repo_url }}/{{ maps_branch }}/osm-source/test-page/build/main.js"
    - "{{ osm_repo_url }}/{{ maps_branch }}/osm-source/test-page/build/index.html"

- name: Fetch the javascript bundle with openlayers for Viewer page
# At this point, fetches from github.com/georgejhunt/maps from {{ maps_branch }} branch
  get_url:
    url: "{{ osm_repo_url }}/{{ maps_branch }}/osm-source/viewer/build/{{ item }}"
    dest: '{{ vector_map_path }}/viewer/'
  with_items:
      - index.html
      - main.js
      #- main.js.map
      - ../ol-contextmenu.css
      - ../popup.css

- name: Copy the map installer mbtiles
  get_url:
    url: "{{ map_catalog_url }}/planet_z0-z6_2019.mbtiles"
    dest: '{{ vector_map_path }}/installer/'

- name: Create a synlink from tiles to detail.mbtiles
  file:
      src: '{{ vector_map_path }}/installer/planet_z0-z6_2019.mbtiles'  
      dest: '{{ vector_map_path }}/installer/detail.mbtiles'
      state: link

- name: Fetch the javascript bundle for map installer
  get_url:
    url: "{{ osm_repo_url }}/{{ maps_branch }}/osm-source/installer/build/{{ item }}"
    dest: '{{ vector_map_path }}/installer/'
  with_items:
      - index.html
      - main.js
      - ../map.css
      - ../installer_functions.js
      - ../tileserver.php
      - ../style-osm.json

#  get_url:
#    url: "{{ osm_repo_url }}/osm-source/regional-base/build/index.html"
#    dest: '{{ vector_map_path }}/maplist/index.html'

- name: Copy the common assets for the general purpose map viewer
  copy: src={{ item }}
        dest="{{ vector_map_path }}/viewer/assets"
        mode=0644
        owner=root
        group=root
  with_fileglob:
        - assets/*

- name: Place a link to bboxes.geojson for Admin Console
  file: 
      src: "{{ vector_map_path }}/viewer/assets/bboxes.geojson"
      dest: "{{ vector_map_path }}/maplist/assets/bboxes.geojson"
      state: link
      force: True
      
- name: Place a link to countries.json for Admin Console
  file: 
      src: "{{ vector_map_path }}/viewer/assets/countries.json"
      dest: "{{ vector_map_path }}/maplist/assets/countries.json"
      state: link
      force: True
      
- name: Copy the fonts for the general purpose map viewer
  copy: src={{ item }}
        dest="{{ doc_root }}/common/fonts/"
        mode=0644
        owner=root
        group=root
  with_fileglob:
        - fonts/*

- name: Copy the php tile server for the general purpose map viewer
  copy: src={{ item }}
        dest="{{ vector_map_path }}/viewer/"
        mode=0644
        owner=root
        group=root
  with_items:
      - tileserver.php
      - searchapi.php
      - mbtileinfo.php

- name: Install the script to update osm catalog
  template:
    src: iiab-update-map
    dest: /usr/bin/iiab-update-map
    mode: "0755"

- name: Copy the redirect to the test page -- delete this if more than one map
  copy:
    force: no
    src: test-index.redirect
    dest: "{{ vector_map_path }}/index.html"
  #when: not osm_redirect.stat.exists

- name: Get packages necessary for map installation
  package:
      state: present
      name:
         - python3-wget
         - "php{{ php_version }}-sqlite3"
         - python3-geojson

- name: Copy a scripts to download tiles
  copy:
      src: '{{ item }}'
      dest: /usr/bin/
      mode: 0755
  with_items:
      - iiab-install-map-region
      - iiab-extend-sat.py

- name: Copy a script to initialize init.json from map-catalog.json
  copy:
      src: iiab-make-init.py
      dest: /usr/bin/
      mode: 0755

- name: Install the World Map to zoom 10
  shell: iiab-install-map-region
  when: osm_vector_maps_enabled | bool

- name: Install /etc/nginx/osm-vector-maps-nginx.conf from template
  template:
    src: osm-vector-maps-nginx.conf.j2
    dest: "/etc/nginx/conf.d/osm-vector-maps-nginx.conf"
  when:
    osm_vector_maps_install | bool

- name: Disable Osm maps
  file:
    path: /etc/nginx/conf.d.osm-vector-maps-nginx.conf
    state: absent
  when:
    not osm_vector_maps_install
