#!/bin/bash -x
# Turn off URL recording mode, and return to serving with apache2

kill $(cat /opt/iiab/captive-portal/capture-wsgi.pid)
awk '{print("address=/" $1 "/172.18.96.1")}' /opt/iiab/captive-portal/checkurls > /etc/dnsmasq.d/capture
awk '{print("ServerAlias ",$1)}' /opt/iiab/captive-portal/checkurls > /etc/apache2/capture
